# Generated by Django 4.2.2 on 2024-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=255)),
                ('monthly_salary', models.BigIntegerField()),
                ('approved_limit', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField(null=True)),
                ('l_id', models.IntegerField()),
                ('loan_amount', models.BigIntegerField()),
                ('tenure', models.IntegerField()),
                ('interest_rate', models.IntegerField(null=True)),
                ('monthly_payment', models.IntegerField()),
                ('emi_on_time', models.IntegerField()),
                ('date_of_approval', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
