# Generated by Django 4.2.2 on 2024-02-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
